apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcontribcol
  namespace: signoz-demo
  labels:
    app: otelcontribcol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcontribcol
  template:
    metadata:
      labels:
        app: otelcontribcol
    spec:
      serviceAccountName: otelcontribcol
      containers:
        - name: otelcontribcol
          image: otel/opentelemetry-collector-contrib:0.91.0
          args:
            - "--config=/conf/config.yaml"
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /conf
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: config
          configMap:
            name: otelcontribcol
            items:
              - key: config.yaml
                path: config.yaml
      nodeSelector:
        kubernetes.io/os: linux
